### ISSUE TITLE
Entrega 2.2: Feedback execução

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#12]
Observação geral sobre o projeto:
* Jogo está evoluindo na construção das histórias, mas problemas relatados nas entregas anteriores não estão sendo tratados. Lembre-se que, além de funcionar, o jogo precisa seguir os conceitos de OO e especificações do trabalho.

Sobre a execução:
* '+ Mensagem do comando 'ligar' corrigida.
* '+ Agora existem imagens diferentes (apesar de várias serem repetidas).
* '- Existem ambientes cuja saída voltam para eles mesmos.
* '- Comandos 'sair' e 'observar' não funcionam.

**Comment by arlenmendes** [comment]
Corrigido
