### ISSUE TITLE
Entrega 2.2: Fechamento de issues anteriores

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#13]
As Issues abertas em uma entrega devem ser fechadas nas entregas seguintes.
* Algumas coias foram tratadas e continuam abertas.
* Outras continuam pendentes (isso impacta negativamente na nota do trabalho).

Sugiro repassar em todas as Issues anteriores fechando as resolvidas (com os devidos comentários) e resolvendo as abertas.

**Comment by arlenmendes** [comment]
Feito.
