### ISSUE TITLE
Extensão do Diagrama de Classes

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#2]
Não foi possível avaliar o diagrama de classes. Envie em PDF para que seja possível dar a nota do Trabalho 1.

**Comment by caburu** [comment]
Entrega 2.1: arquivo PDF solicitado não foi enviado.

**Comment by caburu** [comment]
Entrega 2.2: até hoje não foi enviado o diagrama em PDF. Esse problema é **grave**.

**Comment by arlenmendes** [comment]
Corrigido
