### ISSUE TITLE
Problemas com Javadoc

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#3]
Javadoc enviado, mas está incompleto:
- Diversos métodos e construtores sem comentários.
- Alguns têm comentário apenas do retorno mas não o método em si.
- Arquivos do javadoc foram colocados dentro da pasta de código (fica aparecendo como pacote no Netbeans).

**Comment by caburu** [comment]
Entrega 2.1: Problemas com Javadoc continuam (apenas localização da pasta foi corrigida).

**Comment by caburu** [comment]
Entrega 2.2: Problemas com Javadoc continuam.

**Comment by arlenmendes** [comment]
Corrigidos
