### ISSUE TITLE
Observações gerais sobre o código

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#6]
- Constantes relacionadas a status de portas não deveriam estar na classe Jogo. Além disso, elas deveriam ser números inteiros ou enumeradores.
- Verificar erros de ortografia no código e na documentação.
- Para saber se o item do paciente é o mesmo do status da saída está sendo feita comparação de Strings (tipagem fraca). Poderia ser através de um método temItem que recebesse o item, por exemplo.
- É necessário revisar o comentário que explica a classe Ambiente.
- Em Ambiente e Paciente evite o nome setItem, pois na verdade os métodos não mudam/substituem um item e sim adicionam mais um a uma coleção.
  - Além disso, tais métodos não deveriam receber o nome do item, uma vez que elees poderiam pegar o nome diretamente do parâmetro item.

**Comment by caburu** [comment]
Entrega 2.1: Problemas relatados continuam.

**Comment by caburu** [comment]
Entrega 2.2: Maior parte dos itens relacionados acima continuam pendentes.

**Comment by arlenmendes** [comment]
Problemas resolvidos, apenas o terceiro tópico que não. Pois a única forma que encontrei de validar foi essa. Não consegui encontrar uma forma efetiva para enumerar os status.
