### ISSUE TITLE
Falta uso efetivo do Polimorfismo

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#7]
Apesar de existirem subclasses no código, não existe uso efetivo de Polimorfismo.
- Subclasse PortaoGaragem não faz sentido (não adiciona nada à superclasse e está sendo usada com instanceof). Do jeito que a lógica foi pensada ele poderia ser um objeto Saida com referência guardada pela classe Jogo.
- Apesar de existirem coleções e itens, os itens usados nessas coleções são todos da superclasse.
  - Gerador é usado apenas diretamente com se próprio tipo.

Falta portanto, o uso de métodos polimórficos.

**Comment by caburu** [comment]
Entrega 2.1: Problemas relatados continuam.

**Comment by caburu** [comment]
Entrega 2.2: problema relatado continua e ele é **grave**.

**Comment by arlenmendes** [comment]
Método polimórfico adicionado na classe PortãoGaragem
