### ISSUE TITLE
Entrega 2.1: Feedback execução

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#8]
Observação geral sobre o projeto:
* É necessário investir tempo para entendimento e implementação dos conceitos corretos de OO. Além do jogo funcionar é necessária a utilização adequada dos conceitos.

Sobre  a execução:
* '+ No geral OK, funciona corretamente.
* '+ Usa caixas de diálogo.
* '- Problema com comando 'ligar' não foi corrigido.
* '- Imagem dos ambientes é sempre a mesma.
* '+ Corrigido problema com mensagem de saida bloqueada

**Comment by arlenmendes** [comment]
Corrigidos
