### ISSUE TITLE
Entrega 2.1: Problema nas camadas MVC

### ISSUE THREAD

**Issue by caburu** [arlenmendes/terremoto#9]
- No Padrão MVC a regra de negócios é representada pela Model. Assim, as classes Jogo e Ambiente (que possuem a essência da regra de negócio do Jogo) não podem estar na camada Controller.
- Como consequência a classe Jogo não poderia conhecer as Views.
- Além disso a História 1 deixa claro que a regra de negócio (lógica do jogo) não pode ter nehuma interação com o usuário.

Sugestão de leitura: http://codigofonte.uol.com.br/artigos/aprenda-a-arquitetura-mvc

**Comment by caburu** [comment]
Problema ainda pendente na entrega 2.2.

**Comment by arlenmendes** [comment]
Corrigido. Alterado para camada de serviço, a camada Controller
